### PR TITLE
Handle special characters that would not ordinarily be in an ID on a jstree query

### LINKED ISSUE #26: Greening of the fields fails occasionally
After a tag is successfully applied, the appropriate field in the central pane should turn green. This is not happening in some cases, for example:

On trout merge, select user-4, read-only-1 and a dataset in such a manner, that under ``Auto Tag`` in the central pane you have at least 2 columns where there are ticks as suggestions in all rows (there must be more than 2 rows).

Accept the suggestion or if the tags are not determined yet, go ``Select New/Existing``, click ok in all dialogs and go for defaults and then go Apply. Usually, these are the fields in the right-most columns which do not go green. This problem is fine if you refresh or revisit the dataset, it is only first-time-after-Apply issue.

screen shot 2015-04-06 at 17 08 37
screen shot 2015-04-06 at 17 28 00

### PR DESCRIPTION
**Pull request by dpwrussell**
In this case, it was a semicolon, but there are a few other characters that might cause this which need to be escaped when used in a jquery selector. This fixes them all.

Resolves #26

### CODE REVIEW

**Comment by dpwrussell** [comment]
@pwalczysko I can't test on trout as I can't get inside the firewall, but this should fix it. Let me know?

Cheers

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [WEBTAGGING-merge/label=seabass#295](https://ci.openmicroscopy.org/job/WEBTAGGING-merge/label=seabass/295/). See the [console output](https://ci.openmicroscopy.org/job/WEBTAGGING-merge/label=seabass/295/consoleText) for more details.
Possible conflicts:
  - Conflict detection failed
    - None

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [WEBTAGGING-merge/label=trout#295](https://ci.openmicroscopy.org/job/WEBTAGGING-merge/label=trout/295/). See the [console output](https://ci.openmicroscopy.org/job/WEBTAGGING-merge/label=trout/295/consoleText) for more details.
Possible conflicts:
  - Conflict detection failed
    - None

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [WEBTAGGING-merge/label=octopus#295](https://ci.openmicroscopy.org/job/WEBTAGGING-merge/label=octopus/295/). See the [console output](https://ci.openmicroscopy.org/job/WEBTAGGING-merge/label=octopus/295/consoleText) for more details.
Possible conflicts:
  - Conflict detection failed
    - None

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [WEBTAGGING-merge/label=seabass#296](https://ci.openmicroscopy.org/job/WEBTAGGING-merge/label=seabass/296/). See the [console output](https://ci.openmicroscopy.org/job/WEBTAGGING-merge/label=seabass/296/consoleText) for more details.
Possible conflicts:
  - Conflict detection failed
    - None

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [WEBTAGGING-merge/label=trout#296](https://ci.openmicroscopy.org/job/WEBTAGGING-merge/label=trout/296/). See the [console output](https://ci.openmicroscopy.org/job/WEBTAGGING-merge/label=trout/296/consoleText) for more details.
Possible conflicts:
  - Conflict detection failed
    - None

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [WEBTAGGING-merge/label=octopus#296](https://ci.openmicroscopy.org/job/WEBTAGGING-merge/label=octopus/296/). See the [console output](https://ci.openmicroscopy.org/job/WEBTAGGING-merge/label=octopus/296/consoleText) for more details.
Possible conflicts:
  - Conflict detection failed
    - None

**Comment by pwalczysko** [comment]
@dpwrussell : Sure, I will test it, but the conflict must be resolved first.

**Comment by manics** [comment]
Is there a problem with the job? I can merge fine locally:
```
webtagging$ git reset --hard origin/master
HEAD is now at a3c03b0 Merge pull request #24 from dpwrussell/orphaned_support

webtagging$ scc merge master --no-ask --reset -v
2015-09-21 11:44:41,827 [  scc.config] DEBUG Found github.token
2015-09-21 11:44:43,479 [      scc.gh] DEBUG 4954 remaining from 5000 (Reset at 12:09)
2015-09-21 11:44:43,479 [     scc.git] DEBUG Calling 'git rev-parse --show-toplevel'
2015-09-21 11:44:43,485 [     scc.git] DEBUG Check current status
2015-09-21 11:44:43,485 [     scc.git] DEBUG Calling 'git log --oneline -n 1 HEAD'
2015-09-21 11:44:43,490 [     scc.git] DEBUG a3c03b0 Merge pull request #24 from dpwrussell/orphaned_support
2015-09-21 11:44:43,490 [     scc.git] DEBUG Calling 'git submodule status'
2015-09-21 11:44:43,543 [  scc.config] DEBUG Found remote.origin.url
2015-09-21 11:44:44,372 [     scc.git] DEBUG Calling 'git submodule --quiet foreach echo $path'
2015-09-21 11:44:44,436 [     scc.git] DEBUG Resetting...
2015-09-21 11:44:44,436 [     scc.git] DEBUG Calling 'git reset --hard HEAD'
2015-09-21 11:44:44,444 [     scc.git] DEBUG HEAD is now at a3c03b0 Merge pull request #24 from dpwrussell/orphaned_support
2015-09-21 11:44:44,445 [     scc.git] DEBUG Calling 'git submodule update --recursive'
2015-09-21 11:44:44,497 [     scc.git] DEBUG Check current status
2015-09-21 11:44:44,497 [     scc.git] DEBUG Calling 'git log --oneline -n 1 HEAD'
2015-09-21 11:44:44,503 [     scc.git] DEBUG a3c03b0 Merge pull request #24 from dpwrussell/orphaned_support
2015-09-21 11:44:44,503 [     scc.git] DEBUG Calling 'git submodule status'
2015-09-21 11:44:44,555 [   scc.merge] INFO  Merging Pull Request(s) based on master
2015-09-21 11:44:44,555 [   scc.merge] INFO  Including Pull Request(s) opened by any public member of the organization
2015-09-21 11:44:44,555 [   scc.merge] INFO  Including Pull Request(s) labelled as include
2015-09-21 11:44:44,555 [   scc.merge] INFO  Excluding Pull Request(s) labelled as exclude or breaking
2015-09-21 11:44:44,555 [    scc.repo] DEBUG ## PRs found:
2015-09-21 11:44:49,632 [    scc.repo] DEBUG   # PR 33 dpwrussell 'Handle special characters that would not ordinarily be in an ID on a jstree query'
2015-09-21 11:44:50,448 [    scc.repo] DEBUG   # PR 32 dpwrussell 'A non-post processUpdate is now disallowed'
2015-09-21 11:44:52,086 [    scc.repo] DEBUG   # PR 31 dpwrussell 'Added autotag support for old and new jstree'
2015-09-21 11:44:52,087 [    scc.repo] DEBUG ## Branches found:
2015-09-21 11:44:52,087 [     scc.git] DEBUG Get sha1 of %s
2015-09-21 11:44:52,087 [     scc.git] DEBUG Calling 'git rev-parse HEAD'
2015-09-21 11:44:52,093 [     scc.git] DEBUG Calling 'git show-ref --verify --quiet refs/remotes/origin/master'
2015-09-21 11:44:52,098 [     scc.git] DEBUG ## Merging base to ensure closed PRs are included.
2015-09-21 11:44:52,099 [     scc.git] DEBUG Calling 'git log --oneline --first-parent HEAD..origin/master'
2015-09-21 11:44:52,104 [     scc.git] DEBUG Calling 'git merge --ff-only origin/master'
2015-09-21 11:44:52,110 [     scc.git] DEBUG Already up-to-date.

2015-09-21 11:44:52,110 [     scc.git] DEBUG ## Unique users: set([(u'dpwrussell', <github.Repository.Repository object at 0x102a52590>), (u'dpwrussell', <github.Repository.Repository object at 0x1021f1c50>), (u'dpwrussell', <github.Repository.Repository object at 0x102a52110>)])
2015-09-21 11:44:52,110 [     scc.git] DEBUG Calling 'git remote add merge_dpwrussell git://github.com/dpwrussell/webtagging.git'
2015-09-21 11:44:52,117 [     scc.git] DEBUG Fetching remote merge_dpwrussell...
2015-09-21 11:44:52,118 [     scc.git] DEBUG Calling 'git fetch merge_dpwrussell'
2015-09-21 11:44:52,331 [     scc.git] DEBUG From git://github.com/dpwrussell/webtagging
2015-09-21 11:44:52,332 [     scc.git] DEBUG  * [new branch]      exclude_read_only_tag_when_not_owner -> merge_dpwrussell/exclude_read_only_tag_when_not_owner
2015-09-21 11:44:52,332 [     scc.git] DEBUG  * [new branch]      jstree_2015 -> merge_dpwrussell/jstree_2015
2015-09-21 11:44:52,332 [     scc.git] DEBUG  * [new branch]      jstree_speedup_tags_as_filter -> merge_dpwrussell/jstree_speedup_tags_as_filter
2015-09-21 11:44:52,332 [     scc.git] DEBUG  * [new branch]      jstree_tags_as_filter -> merge_dpwrussell/jstree_tags_as_filter
2015-09-21 11:44:52,333 [     scc.git] DEBUG  * [new branch]      master     -> merge_dpwrussell/master
2015-09-21 11:44:52,333 [     scc.git] DEBUG  * [new branch]      non-post-processUpdate -> merge_dpwrussell/non-post-processUpdate
2015-09-21 11:44:52,334 [     scc.git] DEBUG  * [new branch]      octopus_debug -> merge_dpwrussell/octopus_debug
2015-09-21 11:44:52,334 [     scc.git] DEBUG  * [new branch]      orphaned_support -> merge_dpwrussell/orphaned_support
2015-09-21 11:44:52,334 [     scc.git] DEBUG  * [new branch]      projects_datasets_tags -> merge_dpwrussell/projects_datasets_tags
2015-09-21 11:44:52,335 [     scc.git] DEBUG  * [new branch]      restricted_char_in_tagname -> merge_dpwrussell/restricted_char_in_tagname
2015-09-21 11:44:52,335 [     scc.git] DEBUG  * [new branch]      tooltips   -> merge_dpwrussell/tooltips
2015-09-21 11:44:52,339 [     scc.git] DEBUG Get sha1 of %s
2015-09-21 11:44:52,339 [     scc.git] DEBUG Calling 'git rev-parse HEAD'
2015-09-21 11:44:52,345 [     scc.git] DEBUG Calling 'git diff --name-only HEAD...18636ce9863491a9827625b57facfee2b5d5d96d'
2015-09-21 11:44:52,350 [     scc.git] DEBUG Calling 'git rev-parse HEAD'
2015-09-21 11:44:52,355 [     scc.git] DEBUG Calling 'git merge --no-ff -m merge master -Dorg -Snone: PR 31 (Added autotag support for old and new jstree) 18636ce9863491a9827625b57facfee2b5d5d96d'
2015-09-21 11:44:52,366 [     scc.git] DEBUG Merge made by the 'recursive' strategy.
2015-09-21 11:44:52,370 [     scc.git] DEBUG  autotag/templates/autotag/auto_tag_init.js.html | 72 +++++++++++++++++++------
2015-09-21 11:44:52,370 [     scc.git] DEBUG  autotag/templates/autotag/tags_from_names.html  | 72 ++++++++++++++++++-------
2015-09-21 11:44:52,371 [     scc.git] DEBUG Calling 'git diff --name-only HEAD...c832b090f0f934ef0e07b5c91ce39716042fd990'
2015-09-21 11:44:52,371 [     scc.git] DEBUG  2 files changed, 107 insertions(+), 37 deletions(-)
2015-09-21 11:44:52,377 [     scc.git] DEBUG Calling 'git rev-parse HEAD'
2015-09-21 11:44:52,382 [     scc.git] DEBUG Calling 'git merge --no-ff -m merge master -Dorg -Snone: PR 32 (A non-post processUpdate is now disallowed) c832b090f0f934ef0e07b5c91ce39716042fd990'
2015-09-21 11:44:52,394 [     scc.git] DEBUG Merge made by the 'recursive' strategy.
2015-09-21 11:44:52,398 [     scc.git] DEBUG  autotag/views.py | 256 ++++++++++++++++++++++++++++---------------------------
2015-09-21 11:44:52,398 [     scc.git] DEBUG  1 file changed, 129 insertions(+), 127 deletions(-)
2015-09-21 11:44:52,399 [     scc.git] DEBUG Calling 'git diff --name-only HEAD...51224abe31191c245710137def63b140eed60d2b'
2015-09-21 11:44:52,405 [     scc.git] DEBUG Calling 'git rev-parse HEAD'
2015-09-21 11:44:52,410 [     scc.git] DEBUG Calling 'git merge --no-ff -m merge master -Dorg -Snone: PR 33 (Handle special characters that would not ordinarily be in an ID on a jstree query) 51224abe31191c245710137def63b140eed60d2b'
2015-09-21 11:44:52,425 [     scc.git] DEBUG Auto-merging autotag/templates/autotag/tags_from_names.html
2015-09-21 11:44:52,426 [     scc.git] DEBUG Merge made by the 'recursive' strategy.
2015-09-21 11:44:52,430 [     scc.git] DEBUG  autotag/templates/autotag/tags_from_names.html | 4 ++--
2015-09-21 11:44:52,430 [     scc.git] DEBUG  1 file changed, 2 insertions(+), 2 deletions(-)
2015-09-21 11:44:52,430 [     scc.git] DEBUG Calling 'git submodule update'
2015-09-21 11:44:52,481 [     scc.git] DEBUG Get sha1 of %s
2015-09-21 11:44:52,481 [     scc.git] DEBUG Calling 'git rev-parse HEAD'
2015-09-21 11:44:52,486 [     scc.git] DEBUG Calling 'git diff-index --quiet HEAD'
2015-09-21 11:44:52,493 [     scc.git] DEBUG <git.GitRepository object at 0x101817d10> has no local changes
2015-09-21 11:44:52,493 [     scc.git] DEBUG Calling 'git commit --allow-empty -a -n -m merge master -Dorg -Snone

Repository: MicronOxford/webtagging
Already up-to-date.

Merged PRs:
  # PR 31 dpwrussell 'Added autotag support for old and new jstree'
  # PR 32 dpwrussell 'A non-post processUpdate is now disallowed'
  # PR 33 dpwrussell 'Handle special characters that would not ordinarily be in an ID on a jstree query'
'
2015-09-21 11:44:52,504 [     scc.git] DEBUG [master 6de65f6] merge master -Dorg -Snone
2015-09-21 11:44:52,505 [   scc.merge] INFO  Repository: MicronOxford/webtagging
2015-09-21 11:44:52,505 [   scc.merge] INFO  Already up-to-date.
2015-09-21 11:44:52,505 [   scc.merge] INFO
2015-09-21 11:44:52,505 [   scc.merge] INFO  Merged PRs:
2015-09-21 11:44:52,505 [   scc.merge] INFO    # PR 31 dpwrussell 'Added autotag support for old and new jstree'
2015-09-21 11:44:52,505 [   scc.merge] INFO    # PR 32 dpwrussell 'A non-post processUpdate is now disallowed'
2015-09-21 11:44:52,505 [   scc.merge] INFO    # PR 33 dpwrussell 'Handle special characters that would not ordinarily be in an ID on a jstree query'
2015-09-21 11:44:52,505 [   scc.merge] INFO
2015-09-21 11:44:52,505 [   scc.merge] DEBUG Cleaning remote branches created for merging
2015-09-21 11:44:52,505 [     scc.git] DEBUG Calling 'git remote'
2015-09-21 11:44:52,511 [     scc.git] DEBUG Calling 'git remote rm merge_dpwrussell'

```

**Comment by sbesson** [comment]
@manics: it should be fine now, As you saw above, I modified the title of the PR to remove the trailing ellipsis which was causing the merge issue on the CI node. The latest version of this PR should have been included into the nightly merge build.

I am pretty sure this issue has been seen before but I could not reproduce it either locally or using the Jenkins user on one of the nodes which reported the merge conflicts. So I suspect it is specific to the Jenkins environment, likely encoding related.

**Comment by pwalczysko** [comment]
@dpwrussell : All you need for testing is a Tag suggestion which contains a ``.`` (a dot) and `` `` (a space).
My tag suggestion here is ``5.0 data``  (taken from the Path names). But this PR does not fix the problem unfortunately at all. 
@will-moore will specify why in a separate comment.

**Comment by will-moore** [comment]
@dpwrussell This seems to be not working (just looked with Petr at his data). The token name is ```5.0 data``` (contains a . and a space). Your regex does this
```
"5.0 data".replace( /(:|\.|\[|\]|,|;)/g , "\\$1" )
>>> "5\.0 data"
```
but it seems you need an extra ```\```
but the td has ```class='pathTokens token_5.0 data` ```
```$(".5\.0").length``` finds nothing
```$(".token_5\\.0").length``` finds all td

You might have to remove spaces when generating the token classes in Django? And then also remove spaces in the regex, to get 
```
class='pathTokens token_5.0data`
and
$(".token_5\\.0data")
```

**Comment by will-moore** [comment]
Seems like you need a crazy number of backslashes to make this work:
```
"5.0data".replace( /(:|\.|\[|\]|,|;)/g , "\\\\$1" )
"5\\.0data"
```

**Comment by dpwrussell** [comment]
Ok, spaces are more annoying as they are obviously not useable in CSS class names. In retrospect using the tokens as CSS class names was not a good design decision, but I have fixed it for now by converting the spaces to underscores when used in CSS classes.

**Comment by will-moore** [comment]
@dpwrussell That's actually working fine for "5.0 data" now.
But I think that ``` .replace(" ", "_") ``` will only replace the first space in javascript, so if you have multiple spaces this won't work.

**Comment by dpwrussell** [comment]
Good catch, thanks @will-moore

**Comment by dpwrussell** [comment]
@will-moore Fixed for you?

**Comment by will-moore** [comment]
Yes - it was actually working OK before, and the code change looks good for replacing multiple spaces. So, good to merge.

**Pull request merged**
