### PR TITLE
Added autotag support for old and new jstree

### PR DESCRIPTION
**Pull request by dpwrussell**
Updates auto-tag to cope with different jstree version for 5.2, maintaining support for < 5.2 also.

### CODE REVIEW

**Comment by dpwrussell** [comment]
@pwalczysko Addresses your point from https://github.com/openmicroscopy/openmicroscopy/pull/3995

**Comment by will-moore** [comment]
I'm not seeing this included in today's build on eel. @sbesson Is this supposed to get merged and deployed daily on eel & trout?

**Comment by sbesson** [comment]
As discussed earlier, eel was previously deploying `webtagging 1.2.0` across the board. Switched back to using the merge build so that this PR should be deployed across the board tomorrow morning.

**Comment by will-moore** [comment]
This is mostly working fine on eel (5.2.0) except for 1 bug. If I'm viewing the "Autotag" centre panel, viewing a Dataset and I select a Project, the panel goes blank (as expected) but if I re-select the previous Dataset again (or image in it) then it stays blank and doesn't reload. However, it will load again when I then select a different Dataset. I get the same bug if I select multiple images in a Dataset (goes blank and won't re-load until I select a different Dataset).
I see the same behaviour on trout (5.1.4) so I don't know if this was happening before this PR or not?

**Comment by dpwrussell** [comment]
@will-moore Confirmed that additional bug which I will deal with separately.

**Comment by dpwrussell** [comment]
@will-moore Other than the other bug #34, ok to merge?

**Comment by will-moore** [comment]
Yes - good to merge.

**Comment by pwalczysko** [comment]
@dpwrussell : Of course up to you where you want to fix this, there was one more comment on the jstree PR which does not seem to be fixed as yet, https://github.com/openmicroscopy/openmicroscopy/pull/3995#issuecomment-139534416. Should I open a github issue ?

**Comment by dpwrussell** [comment]
@pwalczysko Yes, if you could open another issue and provide as many details as possible? I wasn't actually able to recreate this.

Cheers.

**Comment by pwalczysko** [comment]
@dpwrussell : Opened https://github.com/MicronOxford/webtagging/issues/36

**Pull request merged**
