### PR TITLE
Reengineered autotag

### PR DESCRIPTION
**Pull request by dpwrussell**
Completely redeveloped autotag using React.

* Massive performance improvements
* New frequency of occurrence based filtering mechanism
* Drop support for OMERO.web less than 5.2
* Fix several issues including #36 #29 #25

### CODE REVIEW

**Comment by jburel** [comment]
Note for @hflynn:
When a version of webtagging including this PR is release: 
The following page
https://www.openmicroscopy.org/site/support/partner/omero.webtagging 
will have to be updated to indicate the compatible version of omero i.e. webtagging 1.3.0 support for 5.1.x, 5.2.x
and for webtagging version 1.4.0  omero 5.2.x only

**Comment by hflynn** [comment]
We don't have a downloads page for 1.4.0 as yet (cc @sbesson), probably best to sort that out before I update the product page

**Comment by jburel** [comment]
@hflynn: my comment was more a heads-up since there is no release

**Comment by hflynn** [comment]
Ah sorry! Gotcha.

**Comment by pwalczysko** [comment]
Tested on centos6_py27_apache24 along the lines of the new scenario https://github.com/openmicroscopy/ome-internal/pull/290. Works as expected. Note that new issues were created with bug reports as well as RFEs. https://github.com/MicronOxford/webtagging/issues/47 https://github.com/MicronOxford/webtagging/issues/46 ... - #42

**Comment by pwalczysko** [comment]
Unfortunately, the issue https://github.com/MicronOxford/webtagging/issues/36 is not resolved in the setup reported in the previous comment https://github.com/MicronOxford/webtagging/pull/37#issuecomment-173260223 on Firefox 43.0.4

**Comment by pwalczysko** [comment]
https://github.com/MicronOxford/webtagging/issues/25 is resolved here.

**Comment by pwalczysko** [comment]
Will have to ask @will-moore about https://github.com/MicronOxford/webtagging/issues/29

**Comment by pwalczysko** [comment]
BUG: ? 
There is a complete change in behavour with regard to tokenizing in some cases compared with previous behaviour (without this PR).
Compare the two screenshots below. The names like ``Screen [Shot_2016-01-20 at 18.23.47.png`` will get tokenized in the old version on the underscore and on the first period (dot) in the name, whereas in the new version with this PR in, this is completely ignored.

Old, without this PR
screen shot 2016-01-22 at 14 58 51

New, with this PR
screen shot 2016-01-22 at 14 57 29

**Comment by pwalczysko** [comment]
@dpwrussell : in more general terms Re https://github.com/MicronOxford/webtagging/pull/37#issuecomment-173944006 - what tokenizing behaviour is acutally expected behaviour as of now ? (slashes, underscores .... anything else ?, what is the behaviour when a pure-number group is in the name ?

**Comment by dpwrussell** [comment]
@pwalczysko Until I address #49 I have made it so that the default is to split on any of:
* Whitespace
* Underscore
* Period
* Forwardslash
* Backslash

**Comment by dpwrussell** [comment]
For this PR to progress the remaining issues are #52 and #51.

@will-moore If you have any ideas about #43 that would also be welcome.

**Comment by will-moore** [comment]
I just found that the bundle.js is breaking jQuery tooltip plugins in the webclient.
To test, uninstall autotag or use the 1.3.0 release and webclient tooltips (E.g. on tags in right panel) work OK. But not with this branch. Webclient currently uses $.tooltip from jQuery-ui 1.10.4.
but bundle.js overrides this with it's own $.tooltip with is not compatible.

**Comment by pwalczysko** [comment]
@dpwrussell : This https://github.com/MicronOxford/webtagging/pull/37#issuecomment-176468675 is quite a bit of a problem for us: the tooltips in webclient are not working at all due to this https://trello.com/c/WEIypp9L/62-blocker-tooltip-on-annotations-in-web-missing

**Comment by will-moore** [comment]
This is also the reason that almost all the Robot tests have been failing recently (see https://github.com/openmicroscopy/openmicroscopy/pull/4418) since a different version of jQuery changes the xpath to dialog buttons etc.

**Comment by dpwrussell** [comment]
This is bootstraps doing. I will see what I can do to avoid introducing another jquery which we definitely do not want.

**Comment by will-moore** [comment]
A minor css bug:
The layout of the filter form in webclient is broken by this bit of css in the style block:
```
.toolbar {
    text-align:right;
}
```
This is how it should look:
screen shot 2016-02-02 at 11 12 35

This is how it's broken by the above css:
screen shot 2016-02-02 at 11 12 59

**Comment by will-moore** [comment]
So there's a lot of jQuery UI tooltip conflict discussion at bootstrap. E.g. https://github.com/twbs/bootstrap/issues/7385.
I think it's been fixed by https://github.com/twbs/bootstrap/pull/11966 
allowing you to do:
```
// Do this right after bootstrap loads, before other code tries to use jQuery UI tooltip
$.fn.bootstrapTooltip = $.fn.tooltip.noConflict();

// then can use it like:
$('.tooltip').bootstrapTooltip('show');
```

**Comment by dpwrussell** [comment]
I actually only use bootstrap for one thing (the tag dropdown menu) and I could achieve that with the react-select component which I'm already using I think. I'll give it a try before I try the jquery workaround as it would also reduce the size of bundle.js which is never a bad thing.

**Comment by will-moore** [comment]
@dpwrussell Maybe you could close this PR until you have some fix to the bootstrap issues, since the bugs in the merge build are making it hard to test other web PRs etc. Thanks.

**Comment by dpwrussell** [comment]
@will-moore There is still some cosmetic work to do, but this latest commit should remove the problem.

**Comment by dpwrussell** [comment]
@will-moore @pwalczysko Ok, I think I'm mostly done. So perhaps time for another look.

Cheers

**Comment by will-moore** [comment]
As @pwalczysko pointed out, blocker bug on Safari, which I repeated (Safari 8.0.8)
```
[Error] TypeError: undefined is not a function (evaluating 'Array.from(arr)')
	perform (bundle.js, line 6739)
	batchedUpdates (bundle.js, line 10756)
	batchedUpdates (bundle.js, line 6228)
	_renderNewRootComponent (bundle.js, line 2830)
```

**Comment by pwalczysko** [comment]
I have also a white pane on Internet Explorer 11 (same error as in the Safari case above https://github.com/MicronOxford/webtagging/pull/37#issuecomment-182831232). Tested on Windows 7 machine.

**Comment by pwalczysko** [comment]
Bug: the formatting of the dropdown menu on the blue and pink buttons. See screenshot below. The menu is "squished" into the precise size of the buton. 

screen shot 2016-02-11 at 12 22 31
screen shot 2016-02-11 at 12 22 21

**Comment by pwalczysko** [comment]
The tooltips are okay now in Web, but https://github.com/MicronOxford/webtagging/pull/37#issuecomment-178517457 persists.

**Comment by dpwrussell** [comment]
Ok, I think I've fixed most of those issues.

Not sure about the one with the squished menus, there are CSS rules in place to avoid that specifically. Is this happening for you on all browsers?

**Comment by pwalczysko** [comment]
Squished menus problem is fixed as of today on all browsers (see screenshot below for Safari, similarly for all browsers, the menu is now blue, and fully highlighted, not squished).
screen shot 2016-02-12 at 10 31 53

Note though that Firefox 42 on Win as well as Firefox 43 on Mac ( but not Chrome, not Safari, not IE 11) have strange color scheme on the token suggestions (originally pink buttons are now blue, originally blue ones are white, the green ones remained green).
screen shot 2016-02-12 at 10 42 45


IE 11 on Win 7 has its own issue (not seen anywhere else) with wrong formatting of the slider (partially hidden under the central pane)
webtagging ie 11

**Comment by pwalczysko** [comment]
The Filtering images box fromat https://github.com/MicronOxford/webtagging/pull/37#issuecomment-178517457 is fixed now.

**Comment by pwalczysko** [comment]
The blocking problems on Safari and IE 11 https://github.com/MicronOxford/webtagging/pull/37#issuecomment-182831232 and https://github.com/MicronOxford/webtagging/pull/37#issuecomment-182834307 are fixed now

**Comment by pwalczysko** [comment]
Tooltips in web work as expected.

**Comment by pwalczysko** [comment]
In summary from today's testing:
   - all major bugs seem to be sorted as indicated 
   - the bootstrap x tooltip in web problem is fixed as well 
   - the only remaining issues are the slight IE 11 misformatting (last point in https://github.com/MicronOxford/webtagging/pull/37#issuecomment-183268813) and the Firefox color problem (second point in https://github.com/MicronOxford/webtagging/pull/37#issuecomment-183268813)

Suggestion: have one more look at the Firefox colors issue, this might confuse users a lot, taking into account the popularity of Firefox (issue both on Mac and Win in 2 different Firefox versions)

**Comment by dpwrussell** [comment]
I have fixed the Firefox colouring problem.

I'm not sure what to do about the IE range slider. I don't actually have any windows infrastructure right now to even try this on. Any chance you could have a play @will-moore and see if there is anything we can do that would fix it easily? A CSS rule for height/padding of the IE range slider maybe.

**Comment by pwalczysko** [comment]
@dpwrussell : The Firefox colouring problem is okay now both on Mac as well as Windows.

The IE range slider problem - @will-moore suggested to put onto the element something like ``margin-top: -5px;`` where the ```-5`` is a good compromise over all browsers - we checked that it is working between Firefox and IE11 with ``-5``.

**Comment by dpwrussell** [comment]
I tried that, but it looks rather messy. I've tried doubling the toolbar height instead. Because it lines up with the bottom of the tree toolbar it still looks tidy, but now leaves plenty of room for a) the IE slider, and b) future extra controls (like the separator customizations). I had to fiddle a few other things around in order to do that. How's that look?

**Comment by pwalczysko** [comment]
IE11 on Win7:
ie11 webtagging linup

Firefox on Win7:
firefox on win7

Chrome on Win7
chrome win7

Safari on Mac
screen shot 2016-02-23 at 19 46 54


So I think it looks good.

**Comment by pwalczysko** [comment]
Bug: the slider does not perform in some situations (Safari only, all other browsers okay)
   - take the slider butoon in any position, grabbing the knob and dragging with the mouse-button down
   - drag it to the extreme left as fast as possible, then release the mouse button
   - observe that the previous number is "stuck" on the extreme left position, i.e. when dragging from for example position ``9``, then now also the extreme left position shows ``9`` and so does the central pane follow suit
    - if you cannot see the bug the first time, keep dragging the slider button from extreme left to extreme right and vice versa
    - note that when you move the slider button by clicking into the slider position, this bug does not appear

**Comment by dpwrussell** [comment]
@pwalczysko The reason that it was doing that was an attempt to get around inconsistencies in how range sliders are treated by the various browsers, but I guess it ended up being worse than just letting the browsers do the wrong thing some of the time. It should now work normally on Safari.

According to the standard, the range slider is only supposed to fire the onChange event when the nob is 'dropped', when dragging it. The browsers are all over the map on this, but hopefully it'll get fixed down the line.

**Comment by pwalczysko** [comment]
@dpwrussell : Understood. So you mean that you fixed the behaviour on Safari just now ? Do not see any new commit.

**Comment by dpwrussell** [comment]
Damn airport wifi was playing up, I lost connection right after I posted that and couldn't push. Am UK side now and pushing.

**Comment by dpwrussell** [comment]
This branch is complete.

**Comment by pwalczysko** [comment]
The bug on safari https://github.com/MicronOxford/webtagging/pull/37#issuecomment-187875215 is fixed as tested today on Mac OS 10.10

**Comment by pwalczysko** [comment]
All the bugs and improvements reported here were fixed. The PR is not breaking anything in the mainline.

**Comment by dpwrussell** [comment]
@pwalczysko +1

**Comment by dpwrussell** [comment]
Unless there are any objections, I will merge this tomorrow and do a release.

**Pull request merged**
