### PR TITLE
Update link

### PR DESCRIPTION
**Pull request by jburel**
Point to help instead of plone page
This part of the migration to the new website
cc @hflynn @dpwrussell

### CODE REVIEW

**Comment by hflynn** [comment]
Can you update the links on the PyPI pages too please @dpwrussell ?

**Comment by jburel** [comment]
@hflynn The link needs to be updated in the README
Its content will then be displayed on pypi
I will fix it in this PR

**Comment by jburel** [comment]
@hflynn done

**Comment by hflynn** [comment]
👍

**Comment by dpwrussell** [comment]
Looks good, thanks.

**Pull request merged**
